docs(demos): use a unique ID for an inner Feature App
sinnerschrader/feature-hub pull request #388
Opened 2019-02-27 11:12 UTC by clebert

2019-02-27 11:18 UTC, fahrradflucht commented on packages/demos/src/feature-app-in-feature-app/feature-app-outer.tsx
> +          idSpecifier={JSON.stringify({id, idSpecifier})}
`[id, idSpecifier].join(":")`

2019-02-27 11:19 UTC, unstubbable requested changes

2019-02-27 11:19 UTC, KingHenne commented on docs/guides/feature-app-in-feature-app.md
> +child Feature App, e.g. using its own `idSpecifier` combined with its own `id`.
please switch the two

2019-02-27 11:19 UTC, KingHenne commented on packages/demos/src/feature-app-in-feature-app/feature-app-outer.tsx
> +          idSpecifier={JSON.stringify({id, idSpecifier})}
see comment by @fahrradflucht

2019-02-27 11:22 UTC, unstubbable approved these changes

2019-02-27 11:31 UTC, merged

2026-05-07 09:56 UTC, pachecocordovamoiseseduardo-byte approved these changes