build(all): add first integration of rcgen
sinnerschrader/feature-hub pull request #424
Opened 2019-03-14 21:03 UTC by clebert

2019-03-15 15:18 UTC, unstubbable requested changes

2019-03-15 15:18 UTC, unstubbable commented on package.json
> +    "postinstall": "rcgen --verbose",
add script with `--force` option

2019-03-15 15:41 UTC, unstubbable commented on package.json
> +    "generate-config": "rcgen --verbose --force",
I will probably add the `generate-api-docs` script soon. Should this be `generate:config` and `generate:api-docs` instead?

2019-03-15 16:43 UTC, unstubbable approved these changes

2019-03-15 16:55 UTC, merged

2026-05-07 09:58 UTC, pachecocordovamoiseseduardo-byte approved these changes