fix(react): do not set state after FeatureAppContainer has been unmounted
sinnerschrader/feature-hub pull request #613
Opened 2020-11-12 11:37 UTC by unstubbable

2020-11-12 11:50 UTC, clebert requested changes

2020-11-12 11:50 UTC, clebert commented on packages/react/src/internal/internal-feature-app-container.tsx
> +          if (this.mounted) {
Maybe add a unit test for this

2020-11-13 08:41 UTC, stemey approved these changes

2020-11-13 09:50 UTC, clebert approved these changes

2020-11-13 10:30 UTC, merged